#!/bin/bash

intml=../../intml

expect () {
    result=$(echo "$1" | $intml -p -)
    if [[ "$result" == "$2" ]]; then
        echo "pass: $1  ==>  $2"
    else
        echo "fail: $1  ==>"
        echo "  expected: $2"
        echo "    actual: $result"
    fi
}

# check we order type tuples correctly
expect "type x = a * b * c" "((type x (a * b * c)))"
expect "type x = (a * b) * c" "((type x ((a * b) * c)))"
expect "type x = a * (b * c)" "((type x (a * (b * c))))"

# function types associate to the right
expect "type t = a -> b -> c" "((type t (a -> (b -> c))))"

# unit parens can be separated
expect "let x = (  )" "((let (pattern x) (unit ())))"

expect "let x = [1]" "((let (pattern x) (list ((int 1)))))"
expect "let x = [|1|]" "((let (pattern x) (vector ((int 1)))))"

expect "let rec f x = x" "((recfunc f ((param x)) (var x)))"

expect "let x = match xs with x::_ -> 1 | _ -> 2" \
    "((let (pattern x) (match (var xs) ((pattern cons (pattern x) (pattern _)) (int 1) (pattern _) (int 2)))))"
# same thing but with leading |
expect "let x = match xs with | x::_ -> 1 | _ -> 2" \
    "((let (pattern x) (match (var xs) ((pattern cons (pattern x) (pattern _)) (int 1) (pattern _) (int 2)))))"

# tuples
expect "let x = 1, 2, 3" "((let (pattern x) (tuple ((int 1) (int 2) (int 3)))))"

